# Generated by Django 5.2.12 on 2026-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dictionary',
            name='dictionary__word_12b5c8_idx',
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['word'], name='dictionary__word_2e372b_idx'),
        ),
    ]
