# Generated by Django 5.2.12 on 2026-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_dictionary_dictionary__word_12b5c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='word',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
